apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filecounter-app-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: azurefile
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: filecounter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filecounter
    spec:
      containers:
      - name: filecounter
        image: "quadient.azurecr.io/cloud/filecounter:demo"
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 100Mi
        volumeMounts:
        - name: app-data
          mountPath: /app-data/
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: filecounter-app-data